# Generated by Django 5.1.4 on 2025-03-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='metacritic_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='steam_rating_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
